apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cloud-native-spring-bookstore/catalog-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-stagging.yml
    name: catalog-config

images:
  - name: catalog-service
    newName: catalog-service
    newTag: 4.0.0

replicas:
  - name: catalog-service
    count: 2
