apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/cloud-native-spring-bookstore/catalog-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/cloud-native-spring-bookstore/catalog-service
  newTag: 7a91b355076c58b6cddc5ac429ed192847ec16e4

replicas:
- count: 2
  name: catalog-service
